     name: Run Python Script
on:
schedule:
  - cron: "0 2 * * 6"
    
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"

  

